# Generated by Django 4.0.4 on 2022-08-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PanelConformeBET3',
        ),
    ]
