# Generated by Django 4.0.4 on 2022-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_faculty_member',
            field=models.BooleanField(default=False),
        ),
    ]
