# Generated by Django 4.0.4 on 2022-08-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0003_studentleader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PanelConformeBET3',
        ),
        migrations.DeleteModel(
            name='PanelInvitationBET3',
        ),
        migrations.DeleteModel(
            name='PanelInvitationBET3Declined',
        ),
        migrations.DeleteModel(
            name='StudentLeader',
        ),
    ]
