# Generated by Django 4.0.4 on 2022-07-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0005_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_adminstrator',
            new_name='is_administrator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_developer',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
