# Generated by Django 4.0.4 on 2022-08-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0005_studentleader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentGroupMember',
        ),
    ]
