# Generated by Django 4.0.4 on 2022-08-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0005_panelconformebet3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PanelConformeBET3',
        ),
        migrations.DeleteModel(
            name='ResearchTitle',
        ),
    ]
