# Generated by Django 4.0.4 on 2022-07-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0006_rename_is_adminstrator_user_is_administrator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_derpartment_head',
            new_name='is_department_head',
        ),
    ]
