# Generated by Django 4.0.4 on 2022-08-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0007_studentgroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleader',
            name='research_title_defense_date',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studentleader',
            name='research_title_defense_start_end',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studentleader',
            name='research_title_defense_start_time',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
