# Generated by Django 4.0.4 on 2022-07-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0007_rename_is_derpartment_head_user_is_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
