# Generated by Django 4.0.4 on 2022-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0007_panelconformebet3_researchtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_leader_username', models.CharField(max_length=256)),
                ('student_leader_name', models.CharField(max_length=256)),
                ('student_member_username', models.CharField(max_length=256)),
                ('student_member_name', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('course_major_abbr', models.CharField(max_length=256)),
            ],
        ),
    ]
