# Generated by Django 4.0.4 on 2022-08-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0008_studentgroupmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
