# Generated by Django 4.0.4 on 2022-07-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0009_user_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('course_major_abbr', models.CharField(max_length=256)),
            ],
        ),
    ]
