# Generated by Django 4.0.4 on 2022-08-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0009_user_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelInvitationBET3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_leader_username', models.CharField(max_length=256)),
                ('dit_head_name', models.CharField(max_length=256)),
                ('dit_head_response', models.CharField(max_length=256)),
                ('panel_member_username_1', models.CharField(max_length=256)),
                ('panel_member_name_1', models.CharField(max_length=256)),
                ('panel_member_response_1', models.CharField(max_length=256)),
                ('panel_member_response_date_1', models.CharField(max_length=256)),
                ('panel_member_username_2', models.CharField(max_length=256)),
                ('panel_member_name_2', models.CharField(max_length=256)),
                ('panel_member_response_2', models.CharField(max_length=256)),
                ('panel_member_response_date_2', models.CharField(max_length=256)),
                ('panel_member_username_3', models.CharField(max_length=256)),
                ('panel_member_name_3', models.CharField(max_length=256)),
                ('panel_member_response_3', models.CharField(max_length=256)),
                ('panel_member_response_date_3', models.CharField(max_length=256)),
                ('panel_member_username_4', models.CharField(max_length=256)),
                ('panel_member_name_4', models.CharField(max_length=256)),
                ('panel_member_response_4', models.CharField(max_length=256)),
                ('panel_member_response_date_4', models.CharField(max_length=256)),
                ('panel_member_username_5', models.CharField(max_length=256)),
                ('panel_member_name_5', models.CharField(max_length=256)),
                ('panel_member_response_5', models.CharField(max_length=256)),
                ('panel_member_response_date_5', models.CharField(max_length=256)),
                ('student_member_username_1', models.CharField(max_length=256)),
                ('student_member_name_1', models.CharField(max_length=256)),
                ('student_member_username_2', models.CharField(max_length=256)),
                ('student_member_name_2', models.CharField(max_length=256)),
                ('student_member_username_3', models.CharField(max_length=256)),
                ('student_member_name_3', models.CharField(max_length=256)),
                ('student_member_username_4', models.CharField(max_length=256)),
                ('student_member_name_4', models.CharField(max_length=256)),
                ('student_member_username_5', models.CharField(max_length=256)),
                ('student_member_name_5', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('course_major_abbr', models.CharField(max_length=256)),
                ('research_title_1', models.CharField(max_length=256)),
                ('research_title_2', models.CharField(max_length=256)),
                ('research_title_3', models.CharField(max_length=256)),
                ('research_title_4', models.CharField(max_length=256)),
                ('research_title_5', models.CharField(max_length=256)),
                ('form_date_submitted', models.CharField(max_length=256)),
                ('defense_date', models.CharField(max_length=256)),
                ('defense_start_time', models.CharField(max_length=256)),
                ('defense_end_time', models.CharField(max_length=256)),
                ('form_status', models.CharField(max_length=256)),
            ],
        ),
    ]
