# Generated by Django 4.0.4 on 2022-07-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0010_studentcoursemajor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='middle_initial',
            new_name='middle_name',
        ),
    ]
