# Generated by Django 4.0.4 on 2022-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0010_panelinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('suffix', models.CharField(blank=True, max_length=256)),
                ('department', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('course_major_abbr', models.CharField(max_length=256)),
                ('bet3_subject_teacher_username', models.CharField(max_length=256)),
                ('bet3_subject_teacher_name', models.CharField(max_length=256)),
                ('bet3_status', models.CharField(max_length=256)),
                ('bet5_subject_teacher_username', models.CharField(blank=True, max_length=256)),
                ('bet5_subject_teacher_name', models.CharField(blank=True, max_length=256)),
                ('bet5_status', models.CharField(blank=True, max_length=256)),
                ('current_subject', models.CharField(max_length=256)),
                ('is_user', models.BooleanField(default=True)),
                ('is_student', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='StudentGroupMembers',
            new_name='StudentGroupMember',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
    ]
