# Generated by Django 4.0.4 on 2022-07-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0012_panelconformebet3_alter_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='honorific',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
