# Generated by Django 4.0.4 on 2022-08-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0012_rename_research_title_defense_start_end_bet3panelinvitation_research_title_defense_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet3panelinvitation',
            name='course_major_abbr',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
