# Generated by Django 4.0.4 on 2022-08-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0013_bet3panelinvitation_course_major_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleader',
            name='bet3_panel_invitation_status',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studentleader',
            name='group_members_status',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studentleader',
            name='research_titles_status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
