# Generated by Django 4.0.4 on 2022-07-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0014_remove_user_major'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PanelConformeBET3',
        ),
    ]
