# Generated by Django 4.0.4 on 2022-08-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0014_studentleader_bet3_panel_invitation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_leader_username', models.CharField(max_length=256)),
                ('file_path', models.CharField(max_length=256)),
            ],
        ),
    ]
