# Generated by Django 4.0.4 on 2022-07-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0015_delete_panelconformebet3'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelConformeBET3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_leader_username', models.CharField(max_length=256)),
                ('dept_head', models.CharField(max_length=256)),
                ('dept_head_status', models.CharField(max_length=256)),
                ('panel_member_1', models.CharField(max_length=256)),
                ('panel_member_2', models.CharField(max_length=256)),
                ('panel_member_3', models.CharField(max_length=256)),
                ('panel_member_4', models.CharField(max_length=256)),
                ('panel_member_5', models.CharField(max_length=256)),
                ('panel_member_status_1', models.CharField(max_length=256)),
                ('panel_member_status_2', models.CharField(max_length=256)),
                ('panel_member_status_3', models.CharField(max_length=256)),
                ('panel_member_status_4', models.CharField(max_length=256)),
                ('panel_member_status_5', models.CharField(max_length=256)),
                ('student_member_1', models.CharField(max_length=256)),
                ('student_member_2', models.CharField(max_length=256)),
                ('student_member_3', models.CharField(max_length=256)),
                ('student_member_4', models.CharField(max_length=256)),
                ('student_member_5', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('research_title', models.CharField(max_length=256)),
                ('date_submitted', models.CharField(max_length=256)),
                ('form_status', models.CharField(max_length=256)),
            ],
        ),
    ]
