# Generated by Django 4.0.4 on 2022-08-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0015_defenseschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PanelInvitationBET3',
        ),
    ]
