# Generated by Django 4.0.4 on 2022-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0015_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtitle',
            name='accepted',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='deferred',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='revise_title',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='suggested_title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
