# Generated by Django 4.0.4 on 2022-07-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0016_panelconformebet3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('student_leader_username', models.CharField(max_length=256)),
                ('student_leader_name', models.CharField(max_length=256)),
            ],
        ),
    ]
