# Generated by Django 4.0.4 on 2022-08-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0017_bet3researchtitledefenseform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BET3ResearchTitleDefenseForm',
        ),
    ]
