# Generated by Django 4.0.4 on 2022-08-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0020_bet3researchtitlevote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BET3ResearchTitleDefenseForm',
        ),
    ]
