# Generated by Django 4.0.4 on 2022-08-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0021_declinedpanelinvitationbet3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeclinedPanelInvitationBET3',
        ),
        migrations.DeleteModel(
            name='PanelInvitationBET3',
        ),
    ]
