# Generated by Django 4.0.4 on 2022-08-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0023_declinedform_panelinvitation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanelInvitationBET3',
            new_name='PanelInvitationBET3',
        ),
        migrations.RenameModel(
            old_name='DeclinedForm',
            new_name='PanelInvitationBET3Declined',
        ),
    ]
