# Generated by Django 4.0.4 on 2022-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0023_rename_panel_status_bet3researchtitledefenseform_panel_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet3researchtitledefenseform',
            name='subject_teacher_full_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='bet3researchtitledefenseform',
            name='subject_teacher_username',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
