# Generated by Django 4.0.4 on 2022-08-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0024_bet3researchtitledefenseform_subject_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet3researchtitledefenseform',
            name='defense_date',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='bet3researchtitledefenseform',
            name='defense_end_time',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='bet3researchtitledefenseform',
            name='defense_start_time',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
