# Generated by Django 4.0.4 on 2022-08-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0025_bet3researchtitledefenseform_defense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet3panelinvitation',
            name='subject_teacher_full_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='bet3panelinvitation',
            name='subject_teacher_username',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
