# Generated by Django 4.0.4 on 2022-08-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0025_panelinvitationbet3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefenseSchedule',
            new_name='DefensSchedule',
        ),
        migrations.DeleteModel(
            name='PanelInvitationBET3',
        ),
    ]
