# Generated by Django 4.0.4 on 2022-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0027_studentleader_title_defense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchtitle',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='researchtitle',
            name='deferred',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='researchtitle',
            name='revise_title',
            field=models.IntegerField(default=0),
        ),
    ]
