# Generated by Django 4.0.4 on 2022-08-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0028_rename_defensschedule_defenseschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelinvitationbet3',
            name='accept_count',
            field=models.IntegerField(max_length=256),
        ),
    ]
