# Generated by Django 4.0.4 on 2022-09-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0028_alter_researchtitle_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet3panelinvitation',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
