# Generated by Django 4.0.4 on 2022-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0030_researchtitle_old_research_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BET3PanelInvitationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_leader_username', models.CharField(max_length=256)),
                ('student_leader_full_name', models.CharField(max_length=256)),
                ('course_major_abbr', models.CharField(blank=True, max_length=256)),
                ('dit_head_username', models.CharField(max_length=256)),
                ('dit_head_full_name', models.CharField(max_length=256)),
                ('dit_head_response', models.CharField(max_length=256)),
                ('dit_head_response_date', models.CharField(max_length=256)),
                ('panel_username', models.CharField(max_length=256)),
                ('panel_full_name', models.CharField(max_length=256)),
                ('panel_response', models.CharField(max_length=256)),
                ('panel_response_date', models.CharField(max_length=256)),
                ('panel_attendance', models.CharField(blank=True, max_length=256)),
                ('research_title_defense_date', models.CharField(blank=True, max_length=256)),
                ('research_title_defense_start_time', models.CharField(blank=True, max_length=256)),
                ('research_title_defense_end_time', models.CharField(blank=True, max_length=256)),
                ('form_date_sent', models.CharField(max_length=256)),
                ('form_status', models.CharField(max_length=256)),
                ('form', models.CharField(max_length=256)),
                ('subject_teacher_username', models.CharField(blank=True, max_length=256)),
                ('subject_teacher_full_name', models.CharField(blank=True, max_length=256)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BET3ResearchTitleDefenseFormLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_leader_username', models.CharField(max_length=256)),
                ('student_leader_full_name', models.CharField(max_length=256)),
                ('course_major_abbr', models.CharField(blank=True, max_length=256)),
                ('panel_username', models.CharField(max_length=256)),
                ('panel_full_name', models.CharField(max_length=256)),
                ('panel_attendance', models.CharField(max_length=256)),
                ('is_panel_chairman', models.BooleanField(default=False)),
                ('form_date', models.CharField(max_length=256)),
                ('form_status', models.CharField(max_length=256)),
                ('form', models.CharField(max_length=256)),
                ('subject_teacher_username', models.CharField(blank=True, max_length=256)),
                ('subject_teacher_full_name', models.CharField(blank=True, max_length=256)),
                ('defense_date', models.CharField(blank=True, max_length=256)),
                ('defense_start_time', models.CharField(blank=True, max_length=256)),
                ('defense_end_time', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DefenseScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('student_leader_username', models.CharField(max_length=256)),
                ('student_leader_name', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('form', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('start_time', models.CharField(max_length=256)),
                ('end_time', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTitleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('course_major_abbr', models.CharField(max_length=256)),
                ('student_leader_username', models.CharField(max_length=256)),
                ('student_leader_name', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('date_submitted', models.CharField(max_length=256)),
                ('accepted', models.IntegerField(default=0)),
                ('deferred', models.IntegerField(default=0)),
                ('revise_title', models.IntegerField(default=0)),
                ('suggested_title', models.CharField(blank=True, max_length=256)),
                ('old_research_title', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
