# Generated by Django 4.0.4 on 2022-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0031_bet3panelinvitationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtitlelog',
            name='defense_date',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
