# Generated by Django 4.0.4 on 2022-09-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0032_researchtitlelog_defense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advisee_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
