# Generated by Django 4.0.4 on 2022-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0034_user_advisee_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleader',
            name='adviser_conforme_status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
