# Generated by Django 4.0.4 on 2022-09-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0035_studentleader_adviser_conforme_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleader',
            name='adviser_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studentleader',
            name='adviser_username',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
