# Generated by Django 4.0.4 on 2022-09-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0036_studentleader_adviser_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BET3AdviserConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_leader_username', models.CharField(max_length=256)),
                ('student_leader_full_name', models.CharField(max_length=256)),
                ('research_title', models.CharField(blank=True, max_length=256)),
                ('form_date_submitted', models.CharField(max_length=256)),
                ('dit_head_username', models.CharField(max_length=256)),
                ('dit_head_name', models.CharField(max_length=256)),
                ('dit_head_response', models.CharField(max_length=256)),
                ('dit_head_response_date', models.CharField(max_length=256)),
                ('adviser_username', models.CharField(max_length=256)),
                ('adviser_name', models.CharField(max_length=256)),
                ('adviser_response', models.CharField(max_length=256)),
                ('adviser_response_date', models.CharField(max_length=256)),
            ],
        ),
    ]
