# Generated by Django 4.0.4 on 2022-09-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0037_bet3adviserconforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtitle',
            name='proposal_defense_status',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='title_defense_status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
