# Generated by Django 4.0.4 on 2022-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0038_researchtitle_proposal_defense_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='advisee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='advisee_limit',
            field=models.IntegerField(default=0),
        ),
    ]
