# Generated by Django 4.0.4 on 2022-09-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0041_bet3adviserconforme_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet3adviserconforme',
            name='form_status',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
