# Generated by Django 4.0.4 on 2022-10-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0043_bet3adviserconformelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
