# Generated by Django 4.0.4 on 2022-11-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0044_user_e_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet3panelinvitation',
            name='dit_head_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet3panelinvitation',
            name='panel_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='e_signature',
            field=models.ImageField(blank=True, null=True, upload_to='static/signatures/'),
        ),
    ]
