# Generated by Django 4.0.4 on 2022-11-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0045_bet3panelinvitation_dit_head_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet3panelinvitationlog',
            name='dit_head_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet3panelinvitationlog',
            name='panel_signature',
            field=models.BooleanField(default=False),
        ),
    ]
