# Generated by Django 4.0.4 on 2022-11-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0047_bet3researchtitledefenseform_panel_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet3researchtitledefenseform',
            old_name='panel_signature',
            new_name='panel_signature_attach',
        ),
        migrations.RenameField(
            model_name='bet3researchtitledefenseformlog',
            old_name='panel_signature',
            new_name='panel_signature_attach',
        ),
        migrations.AddField(
            model_name='bet3researchtitledefenseform',
            name='panel_signature_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet3researchtitledefenseformlog',
            name='panel_signature_response',
            field=models.BooleanField(default=False),
        ),
    ]
