# Generated by Django 4.0.4 on 2022-11-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0048_rename_panel_signature_bet3researchtitledefenseform_panel_signature_attach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet3researchtitlevote',
            name='start_voting',
            field=models.BooleanField(default=False),
        ),
    ]
