# Generated by Django 4.0.4 on 2022-11-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0049_bet3researchtitlevote_start_voting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet3researchtitlevote',
            name='start_voting',
        ),
        migrations.AddField(
            model_name='bet3researchtitledefenseform',
            name='start_voting',
            field=models.BooleanField(default=False),
        ),
    ]
