# Generated by Django 4.0.4 on 2022-11-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0052_bet3proposaldefensepanelinvitation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet3proposaldefensepanelinvitation',
            old_name='research_title_defense_date',
            new_name='research_proposal_defense_date',
        ),
        migrations.RenameField(
            model_name='bet3proposaldefensepanelinvitation',
            old_name='research_title_defense_end_time',
            new_name='research_proposal_defense_end_time',
        ),
        migrations.RenameField(
            model_name='bet3proposaldefensepanelinvitation',
            old_name='research_title_defense_start_time',
            new_name='research_proposal_defense_start_time',
        ),
        migrations.RenameField(
            model_name='bet3proposaldefensepanelinvitationlogs',
            old_name='research_title_defense_date',
            new_name='research_proposal_defense_date',
        ),
        migrations.RenameField(
            model_name='bet3proposaldefensepanelinvitationlogs',
            old_name='research_title_defense_end_time',
            new_name='research_proposal_defense_end_time',
        ),
        migrations.RenameField(
            model_name='bet3proposaldefensepanelinvitationlogs',
            old_name='research_title_defense_start_time',
            new_name='research_proposal_defense_start_time',
        ),
    ]
