# Generated by Django 4.0.4 on 2022-11-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0056_bet3researchproposaldefensecritique_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BET3PanelInvitation',
            new_name='TitlePanelInvitation',
        ),
    ]
