# Generated by Django 4.0.4 on 2022-11-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0057_rename_bet3panelinvitation_titlepanelinvitation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BET3ResearchProposalDefenseCritique',
            new_name='ProposalDefenseCritique',
        ),
    ]
