# Generated by Django 4.0.4 on 2022-11-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0058_rename_bet3researchproposaldefensecritique_proposaldefensecritique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BET3ResearchProposalDefenseFormLogs',
            new_name='ProposalDefenseForm',
        ),
        migrations.RenameModel(
            old_name='BET3ResearchProposalDefenseForm',
            new_name='ProposalDefenseFormLogs',
        ),
    ]
