# Generated by Django 4.0.4 on 2022-11-25 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0059_rename_bet3researchproposaldefenseformlogs_proposaldefenseform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BET3ProposalDefensePanelInvitation',
            new_name='ProposalPanelInvitation',
        ),
        migrations.RenameModel(
            old_name='BET3ProposalDefensePanelInvitationLogs',
            new_name='ProposalPanelInvitationLog',
        ),
        migrations.RenameModel(
            old_name='BET3ResearchTitleDefenseForm',
            new_name='TitleDefenseForm',
        ),
    ]
