# Generated by Django 4.0.4 on 2022-11-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0060_rename_bet3proposaldefensepanelinvitation_proposalpanelinvitation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BET3ResearchTitleDefenseFormLog',
            new_name='TitleDefenseFormLog',
        ),
        migrations.RenameModel(
            old_name='BET3PanelInvitationLog',
            new_name='TitlePanelInvitationLog',
        ),
        migrations.RenameModel(
            old_name='BET3ResearchTitleVote',
            new_name='TitleVote',
        ),
    ]
