# Generated by Django 4.0.4 on 2022-11-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0061_rename_bet3researchtitledefenseformlog_titledefenseformlog_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BET3AdviserConforme',
            new_name='AdviserConforme',
        ),
        migrations.RenameModel(
            old_name='BET3AdviserConformeLog',
            new_name='AdviserConformeLog',
        ),
        migrations.RenameModel(
            old_name='ProposalDefenseFormLogs',
            new_name='ProposalDefenseFormLog',
        ),
    ]
