# Generated by Django 4.0.4 on 2022-11-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0062_rename_bet3adviserconforme_adviserconforme_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProposalDefenseCritique',
        ),
    ]
