# Generated by Django 4.0.4 on 2022-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0064_proposaldefensecritique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposaldefenseform',
            old_name='start_comment',
            new_name='end_critique',
        ),
        migrations.AddField(
            model_name='proposaldefenseform',
            name='end_voting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaldefenseform',
            name='start_critique',
            field=models.BooleanField(default=False),
        ),
    ]
