# Generated by Django 4.0.4 on 2022-11-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0065_rename_start_comment_proposaldefenseform_end_critique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposaldefenseformlog',
            old_name='start_comment',
            new_name='start_critique',
        ),
        migrations.AddField(
            model_name='proposaldefenseformlog',
            name='end_critique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaldefenseformlog',
            name='end_voting',
            field=models.BooleanField(default=False),
        ),
    ]
