# Generated by Django 4.0.4 on 2022-11-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0066_rename_start_comment_proposaldefenseformlog_start_critique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldefenseform',
            name='critique_sign_response',
            field=models.BooleanField(default=False),
        ),
    ]
