# Generated by Django 4.0.4 on 2022-11-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0067_proposaldefenseform_critique_sign_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldefenseform',
            name='proposal_defense_response',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
