# Generated by Django 4.0.4 on 2022-11-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0068_proposaldefenseform_proposal_defense_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldefenseform',
            name='research_title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='proposaldefenseformlog',
            name='critique_sign_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaldefenseformlog',
            name='proposal_defense_response',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
