# Generated by Django 4.0.4 on 2022-11-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0072_proposaldefenseformlog_start_tie_vote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposaldefenseform',
            name='start_tie_vote',
        ),
        migrations.RemoveField(
            model_name='proposaldefenseform',
            name='tie_response',
        ),
        migrations.RemoveField(
            model_name='proposaldefenseformlog',
            name='start_tie_vote',
        ),
        migrations.RemoveField(
            model_name='proposaldefenseformlog',
            name='tie_response',
        ),
    ]
