# Generated by Django 4.0.4 on 2022-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0074_finaldefenseform_finaldefenseformlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleader',
            name='research_final_defense_date',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studentleader',
            name='research_final_defense_end_time',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studentleader',
            name='research_final_defense_start_time',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
