# Generated by Django 4.0.4 on 2022-12-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0078_panelconforme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelconforme',
            name='panel_attendance',
        ),
    ]
