# Generated by Django 4.0.4 on 2022-12-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0079_remove_panelconforme_panel_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleader',
            name='final_panel_conforme',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studentleader',
            name='proposal_panel_conforme',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studentleader',
            name='topic_panel_conforme',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
