# Generated by Django 4.0.4 on 2022-12-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0081_panelconformelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelconformelog',
            old_name='research_title_defense_date',
            new_name='defense_date',
        ),
        migrations.RenameField(
            model_name='panelconformelog',
            old_name='research_title_defense_end_time',
            new_name='defense_end_time',
        ),
        migrations.RenameField(
            model_name='panelconformelog',
            old_name='research_title_defense_start_time',
            new_name='defense_start_time',
        ),
    ]
