# Generated by Django 4.0.4 on 2022-12-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0083_rename_research_title_defense_date_panelconforme_defense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleader',
            name='acknowledgement_receipt',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
