# Generated by Django 4.0.4 on 2022-12-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0085_acknowledgementreceipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acknowledgementreceipt',
            old_name='adviser_ext_full_name',
            new_name='adviser_full_name',
        ),
        migrations.RenameField(
            model_name='acknowledgementreceipt',
            old_name='adviser_ext_response',
            new_name='adviser_response',
        ),
        migrations.RenameField(
            model_name='acknowledgementreceipt',
            old_name='adviser_ext_response_date',
            new_name='adviser_response_date',
        ),
        migrations.RenameField(
            model_name='acknowledgementreceipt',
            old_name='adviser_ext_signature',
            new_name='adviser_signature',
        ),
        migrations.RenameField(
            model_name='acknowledgementreceipt',
            old_name='adviser_ext_username',
            new_name='adviser_username',
        ),
    ]
