# Generated by Django 4.0.4 on 2022-12-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0086_rename_adviser_ext_full_name_acknowledgementreceipt_adviser_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acknowledgementreceipt',
            old_name='subject_teacher_ext_full_name',
            new_name='subject_teacher_full_name',
        ),
        migrations.RenameField(
            model_name='acknowledgementreceipt',
            old_name='subject_teacher_ext_response',
            new_name='subject_teacher_response',
        ),
        migrations.RenameField(
            model_name='acknowledgementreceipt',
            old_name='subject_teacher_ext_response_date',
            new_name='subject_teacher_response_date',
        ),
        migrations.RenameField(
            model_name='acknowledgementreceipt',
            old_name='subject_teacher_ext_signature',
            new_name='subject_teacher_signature',
        ),
        migrations.RenameField(
            model_name='acknowledgementreceipt',
            old_name='subject_teacher_ext_username',
            new_name='subject_teacher_username',
        ),
    ]
