# Generated by Django 4.0.4 on 2023-01-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0087_rename_subject_teacher_ext_full_name_acknowledgementreceipt_subject_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleader',
            name='username',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
