# Generated by Django 4.0.4 on 2023-01-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0088_alter_studentleader_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviserconforme',
            name='thesis_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adviserconformelog',
            name='thesis_completed',
            field=models.BooleanField(default=False),
        ),
    ]
