# Generated by Django 4.0.4 on 2023-01-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0090_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviserconforme',
            name='adviser_response_date_exp',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
