# Generated by Django 4.0.4 on 2023-01-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0093_finaldefensecritique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalDefenseCritique',
        ),
        migrations.DeleteModel(
            name='TitleDefenseCritique',
        ),
        migrations.RemoveField(
            model_name='finaldefenseform',
            name='critique_sign_response',
        ),
        migrations.RemoveField(
            model_name='finaldefenseform',
            name='end_critique',
        ),
        migrations.RemoveField(
            model_name='finaldefenseform',
            name='start_critique',
        ),
        migrations.RemoveField(
            model_name='titledefenseform',
            name='critique_sign_response',
        ),
        migrations.RemoveField(
            model_name='titledefenseform',
            name='end_critique',
        ),
        migrations.RemoveField(
            model_name='titledefenseform',
            name='end_voting',
        ),
        migrations.RemoveField(
            model_name='titledefenseform',
            name='panel_chairman_signature_attach',
        ),
        migrations.RemoveField(
            model_name='titledefenseform',
            name='panel_chairman_signature_response',
        ),
        migrations.RemoveField(
            model_name='titledefenseform',
            name='start_critique',
        ),
        migrations.RemoveField(
            model_name='titledefenseform',
            name='title_defense_response',
        ),
    ]
