# Generated by Django 4.0.4 on 2023-01-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupc_research_defense_form_web_app', '0095_finaldefensecritique_titledefensecritique_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalDefenseCritique',
        ),
    ]
